import type { ExpoConfig } from 'expo/config';
import { version } from './package.json';

const config: { expo: ExpoConfig } = {
  expo: {
    name: 'Medium Unlocker',
    slug: 'medium-unlocker',
    version,
    buildCacheProvider: 'eas',
    orientation: 'portrait',
    icon: './assets/images/icon.png',
    scheme: 'myapp',
    userInterfaceStyle: 'automatic',
    splash: {
      image: './assets/images/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#1a1c24',
    },
    ios: {
      supportsTablet: true,
      bundleIdentifier: 'mediumunlocker',
      userInterfaceStyle: 'automatic',
    },
    android: {
      userInterfaceStyle: 'automatic',
      adaptiveIcon: {
        foregroundImage: './assets/images/icon.png',
        backgroundColor: '#1a1c24',
      },
      package: 'com.TheMythologist.medium_unlocker',
      intentFilters: [
        {
          action: 'VIEW',
          data: [
            { host: 'freedium-mirror.cfd' },
            { scheme: 'https' },
            { pathPattern: '/..*' },
            { pathPattern: '/' },
          ],
          category: ['BROWSABLE', 'DEFAULT'],
        },
        {
          action: 'VIEW',
          data: [
            { host: 'medium.com' },
            { host: '*.medium.com' },

            { host: '500ish.com' },
            { host: 'aninjusticemag.com' },
            { host: 'articles.c-a-s-t.com' },
            { host: 'baos.pub' },
            { host: 'becominghuman.ai' },
            { host: 'betterhumans.pub' },
            { host: 'bettermarketing.pub' },
            { host: 'betterprogramming.pub' },
            { host: 'blackboxofpm.com' },
            { host: 'blog.angular.io' },
            { host: 'blog.bcmhunt.com' },
            { host: 'blog.bitsrc.io' },
            { host: 'blog.blockswap.network' },
            { host: 'blog.devgenius.io' },
            { host: 'blog.faceit.com' },
            { host: 'blog.goodaudience.com' },
            { host: 'blog.growthhackers.com' },
            { host: 'blog.insightdatascience.com' },
            { host: 'blog.jupyter.org' },
            { host: 'blog.mapbox.com' },
            { host: 'blog.matter-labs.io' },
            { host: 'blog.meteor.com' },
            { host: 'blog.mlreview.com' },
            { host: 'blog.producthunt.com' },
            { host: 'blog.prototypr.io' },
            { host: 'blog.qz.com' },
            { host: 'blog.revolution.com' },
            { host: 'blog.sia.tech' },
            { host: 'blog.streamtoken.net' },
            { host: 'blog.trezor.io' },
            { host: 'blog.x.company' },
            { host: 'bootcamp.uxdesign.cc' },
            { host: 'bothsidesofthetable.com' },
            { host: 'brasil.uxdesign.cc' },
            { host: 'brightthemag.com' },
            { host: 'bthechange.com' },
            { host: 'building.theatlantic.com' },
            { host: 'bullshit.ist' },
            { host: 'byrslf.co' },
            { host: 'cafe.belikewise.com' },
            { host: 'chatbotslife.com' },
            { host: 'chatbotsmagazine.com' },
            { host: 'code.likeagirl.io' },
            { host: 'codeburst.io' },
            { host: 'crossingenres.com' },
            { host: 'curiosityneverkilledthewriter.com' },
            { host: 'deepdives.in' },
            { host: 'eand.co' },
            { host: 'ehandbook.com' },
            { host: 'eng.lyft.com' },
            { host: 'entrepreneurshandbook.co' },
            { host: 'facesoffounders.org' },
            { host: 'faun.pub' },
            { host: 'festivalpeak.com' },
            { host: 'gointothestory.blcklst.com' },
            { host: 'heartbeat.comet.ml' },
            { host: 'infosecwriteups.com' },
            { host: 'insiders.fortune.com' },
            { host: 'instagram-engineering.com' },
            { host: 'itnext.io' },
            { host: 'javascript.plainenglish.io' },
            { host: 'jtbd.info' },
            { host: 'levelup.gitconnected.com' },
            { host: 'library.gv.com' },
            { host: 'loremipsum.ueno.co' },
            { host: 'magenta.as' },
            { host: 'medium.datadriveninvestor.com' },
            { host: 'medium.design' },
            { host: 'medium.economist.com' },
            { host: 'medium.engineering' },
            { host: 'medium.muz.li' },
            { host: 'medium.mybridge.co' },
            { host: 'medium.reinvent.net' },
            { host: 'myerotica.com' },
            { host: 'netbasal.com' },
            { host: 'netflixtechblog.com' },
            { host: 'newo.cc' },
            { host: 'news.greylock.com' },
            { host: 'news.legendfantasywar.com' },
            { host: 'open.nytimes.com' },
            { host: 'proandroiddev.com' },
            { host: 'productcoalition.com' },
            { host: 'pub.towardsai.net' },
            { host: 'python.plainenglish.io' },
            { host: 'startupsventurecapital.com' },
            { host: 'stillcrew.com' },
            { host: 'stories.moma.org' },
            { host: 'storyandplanning.com' },
            { host: 'thebelladonnacomedy.com' },
            { host: 'thebolditalic.com' },
            { host: 'thedesignteam.io' },
            { host: 'themakingofamillionaire.com' },
            { host: 'thinkgrowth.org' },
            { host: 'tokeneconomy.co' },
            { host: 'towardsdatascience.com' },
            { host: 'ux.shopify.com' },
            { host: 'uxdesign.cc' },
            { host: 'uxplanet.org' },
            { host: 'virtualrealitypop.com' },
            { host: 'writingcooperative.com' },
            { host: 'www.cantorsparadise.com' },
            { host: 'you.women2.com' },

            { scheme: 'https' },
            { scheme: 'http' },
            { pathPattern: '/..*' },
          ],
          category: ['BROWSABLE', 'DEFAULT'],
        },
        {
          // Non-Medium publishers supported by the Freedium backend
          action: 'VIEW',
          data: [
            // The Athletic
            { host: 'theathletic.com' },
            { host: 'www.theathletic.com' },

            // The New York Times
            { host: 'nytimes.com' },
            { host: 'www.nytimes.com' },

            // The Washington Post
            { host: 'washingtonpost.com' },
            { host: 'www.washingtonpost.com' },

            // Financial Times
            { host: 'ft.com' },
            { host: 'www.ft.com' },

            // The Economist
            { host: 'economist.com' },
            { host: 'www.economist.com' },

            // Reuters
            { host: 'reuters.com' },
            { host: 'www.reuters.com' },

            // Bloomberg
            { host: 'bloomberg.com' },
            { host: 'www.bloomberg.com' },

            { scheme: 'https' },
            { scheme: 'http' },
            { pathPattern: '/..*' },
          ],
          category: ['BROWSABLE', 'DEFAULT'],
        },
      ],
    },
    plugins: ['expo-router', '@react-native-async-storage/expo-with-async-storage', 'expo-font'],
    experiments: {
      typedRoutes: true,
    },
    extra: {
      router: {
        origin: false,
      },
      eas: {
        projectId: 'f2c1cae3-6390-4aa9-8df8-2f92c0993d55',
      },
    },
    owner: 'themythologist',
    githubUrl: 'https://github.com/TheMythologist/medium-unlocker',
  },
};

export default config;
